export const INSTRUMENTS = [
  'Guitarra Eléctrica',
  'Guitarra Acústica',
  'Guitarra Clásica',
  'Bajo Eléctrico',
  'Bajo Acústico',
  'Batería',
  'Percusión',
  'Piano',
  'Teclado',
  'Sintetizador',
  'Violín',
  'Viola',
  'Violonchelo',
  'Contrabajo',
  'Arpa',
  'Trompeta',
  'Trombón',
  'Corno Francés',
  'Tuba',
  'Saxofón Alto',
  'Saxofón Tenor',
  'Saxofón Barítono',
  'Clarinete',
  'Flauta',
  'Oboe',
  'Fagot',
  'Ukelele',
  'Mandolina',
  'Banjo',
  'Acordeón',
  'Armónica',
  'Voz / Vocalista',
  'Producción / DJ',
  'Caja de Ritmos',
  'Theremin',
  'Lap Steel',
  'Pedal Steel',
  'Sitar',
  'Didgeridoo',
]

export const GENRES = [
  'Rock',
  'Rock Alternativo',
  'Rock Clásico',
  'Hard Rock',
  'Punk',
  'Post-Punk',
  'Metal',
  'Heavy Metal',
  'Death Metal',
  'Black Metal',
  'Doom Metal',
  'Nu Metal',
  'Indie',
  'Indie Rock',
  'Indie Pop',
  'Shoegaze',
  'Post-Rock',
  'Math Rock',
  'Pop',
  'Synth-Pop',
  'Dream Pop',
  'Art Pop',
  'K-Pop',
  'Jazz',
  'Jazz Fusión',
  'Bebop',
  'Smooth Jazz',
  'Blues',
  'Blues Rock',
  'Soul',
  'R&B',
  'Funk',
  'Neo-Soul',
  'Gospel',
  'Hip-Hop',
  'Rap',
  'Trap',
  'Lo-Fi',
  'Boom Bap',
  'Electrónica',
  'Techno',
  'House',
  'Drum and Bass',
  'Ambient',
  'IDM',
  'Reggae',
  'Ska',
  'Dub',
  'Reggaeton',
  'Dancehall',
  'Clásica',
  'Contemporánea',
  'Minimalismo',
  'Neoclásica',
  'Folk',
  'Country',
  'Bluegrass',
  'Americana',
  'Flamenco',
  'Salsa',
  'Cumbia',
  'Bossa Nova',
  'Samba',
  'Tango',
  'Experimental',
  'Noise',
  'Avant-Garde',
]
